# -*- coding: utf-8 -*-
"""task 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q7PAA65KiQwv7NcIjnHmleA5rM3Z-2VO
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y != 0:
        return x / y
    else:
        return "Cannot divide by zero."

# Get user input
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Display operation choices
print("Select operation:")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")

# Get user's choice
choice = input("Enter choice (1/2/3/4): ")

# Perform calculation based on user's choice
if choice in ('1', '2', '3', '4'):
    if choice == '1':
        result = add(num1, num2)
        operation = '+'
    elif choice == '2':
        result = subtract(num1, num2)
        operation = '-'
    elif choice == '3':
        result = multiply(num1, num2)
        operation = '*'
    elif choice == '4':
        result = divide(num1, num2)
        operation = '/'

    # Display the result
    print(f"{num1} {operation} {num2} = {result}")
else:
    print("Invalid input. Please enter a valid choice (1/2/3/4).")